version: "3.9"
services:
  chatgptslackbot:
    build:
      context: ./
    image: lrx0014/slack-chatbot:latest
    restart: always
    container_name: slack-chatbot
    env_file:
      - ./variables.env
    ports:
      - 4000:4000
